server:
  port: 9000

spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fish_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wsp0222.
  web:
    resources:
      static-locations: classpath:/static/,file:E:/Desktop/Code/afishing/Fish-Commerce/uploads/
  mvc:
    static-path-pattern: /uploads/**

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.afishing.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload:
    path: E:/Desktop/Code/afishing/Fish-Commerce/uploads/
  access:
    url: /uploads/

# Spring Boot Admin Client
spring.boot.admin.client.url: http://localhost:8080

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
