spring.application.name=service-product
server.port=9000

spring.cloud.nacos.server-addr=127.0.0.1:8848

# MyBatis Plus 配置
mybatis-plus.mapper-locations=classpath:mapper/**/*.xml
mybatis-plus.type-aliases-package=com.afishing.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 数据库配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/fish_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=wsp0222.

# 文件上传配置
file.upload.path=E:/Desktop/Code/afishing/Fish-Commerce/uploads/
file.access.url=/uploads/

# 静态资源映射
spring.web.resources.static-locations=classpath:/static/,file:E:/Desktop/Code/afishing/Fish-Commerce/uploads/
spring.mvc.static-path-pattern=/uploads/**
